language: java
sudo: false
cache:
  directories:
  - $HOME/.m2
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
env:
  - FEDORA_VERSION=3.6.2
  - FEDORA_VERSION=3.7.0
  - FEDORA_VERSION=3.7.1
before_install:
  - wget https://github.com/fcrepo3/fcrepo/releases/download/v3.8.1/install-f3-deps.zip
  - unzip install-f3-deps.zip
  - cd install-f3-deps/lib
  - wget http://alpha.library.yorku.ca/mulgara-core-2.1.12.jar
  - wget http://alpha.library.yorku.ca/mulgara-core-2.1.12.pom
  - wget http://alpha.library.yorku.ca/emory-util-remote-2.1.jar
  - wget http://alpha.library.yorku.ca/emory-util-remote-2.1.pom
  - wget http://alpha.library.yorku.ca/fcrepo-common-3.6.2.jar
  - wget http://alpha.library.yorku.ca/fcrepo-common-3.6.2.pom
  - rm mulgara-core-2.1.13.jar mulgara-core-2.1.13.pom
  - ls
  - cd $TRAVIS_BUILD_DIR/install-f3-deps
  - wget -N http://alpha.library.yorku.ca/install-dependencies.sh
  - ./install-dependencies.sh
  - cd $TRAVIS_BUILD_DIR
script:
  - mvn test -DskipTests=false -Dfedora.version=$FEDORA_VERSION -Ddb.name=drupal_test -Ddb.user=travis -Ddb.pass=""
  - mvn test -DskipTests=false -Dfedora.version=$FEDORA_VERSION -Ddb.name=drupal_test -Ddb.user=postgres -Ddb.pass="" -Ddb.port=5432 -Ddb.class="org.postgresql.Driver" -Ddb.scheme="jdbc:postgresql" -Ddb.group=postgresql -Ddb.artifact=postgresql -Ddb.version="9.1-901.jdbc4"
